"use strict";
const assert = require("node:assert/strict"); const app = require("./app");
let passed = 0; let failed = 0; const jobs = [];
function test(name, fn) { jobs.push({ name, fn }); }
const dealt = []; const faceDown = async (item) => { dealt.push(`${item.side}${item.cardIndex + 1}`); };
async function revealAll(game) { while (game.state === app.GAME_STATES.REVEAL_READY) await game.revealNextCard(async () => {}); }
test("V0.5 economic parameters and betting limits remain intact", () => { const game = new app.BaccaratGameController(); assert.equal(game.account.balance, 100000); game.selectChip(5000); for(let i=0;i<4;i++) assert.equal(game.placeSelectedBet("PLAYER"),true); assert.equal(game.placeSelectedBet("PLAYER"),false); });
test("DEAL automatically sends exactly the initial four face-down cards in order", async () => { dealt.length=0; const game=new app.BaccaratGameController(); game.placeSelectedBet("PLAYER"); await game.prepareDeal(faceDown); assert.deepEqual(dealt,["PLAYER1","BANKER1","PLAYER2","BANKER2"]); assert.equal(game.state,app.GAME_STATES.REVEAL_READY); assert.equal(game.revealedKeys.size,0); assert.equal(game.revealQueue.length,4); assert.equal(game.placeSelectedBet("TIE"),false); });
test("REVEAL flips only one queued card and score state counts revealed cards only", async () => { const game=new app.BaccaratGameController(); game.placeSelectedBet("PLAYER"); await game.prepareDeal(async()=>{}); assert.equal(game.revealedCards.PLAYER.length,0); await game.revealNextCard(async()=>{}); assert.deepEqual([...game.revealedKeys],["PLAYER-0"]); assert.equal(game.revealedCards.PLAYER.length,1); assert.equal(game.revealedCards.BANKER.length,0); });
test("double reveal during one flip cannot advance twice", async () => { const game=new app.BaccaratGameController(); game.placeSelectedBet("PLAYER"); await game.prepareDeal(async()=>{}); let release; const flip=()=>new Promise(resolve=>{release=resolve}); const first=game.revealNextCard(flip); assert.equal(await game.revealNextCard(flip),false); assert.equal(game.currentRevealIndex,0); release(); await first; assert.equal(game.currentRevealIndex,1); });
test("initial four are private until all are revealed, then draw cards auto-deal", async () => { const game=new app.BaccaratGameController(); game.placeSelectedBet("PLAYER"); await game.prepareDeal(async()=>{}); const expectedDraws=game.dealQueue.length-4; assert.equal(game.dealtKeys.size,4); for(let i=0;i<3;i++) await game.revealNextCard(async()=>{}); assert.equal(game.dealtKeys.size,4); await game.revealNextCard(async()=>{}); assert.equal(game.dealtKeys.size,4+expectedDraws); if(expectedDraws) assert.equal(game.state,app.GAME_STATES.REVEAL_READY); });
test("draw cards reuse face-down travel in PLAYER-3 then BANKER-3 order", async () => { let matched=false; for(let attempt=0;attempt<2000&&!matched;attempt++){const calls=[];const game=new app.BaccaratGameController();game.placeSelectedBet("PLAYER");await game.prepareDeal(async item=>calls.push(`${item.side}-${item.cardIndex}`));if(game.dealQueue.length!==6)continue;for(let i=0;i<4;i++)await game.revealNextCard(async()=>{});assert.deepEqual(calls.slice(4),["PLAYER-2","BANKER-2"]);matched=true;}assert.equal(matched,true); });
test("Natural does not create third-card presentation", async () => { const game=new app.BaccaratGameController(); let natural=false; for(let attempt=0;attempt<2000;attempt++){ game.placeSelectedBet("PLAYER"); await game.prepareDeal(async()=>{}); if(game.roundResult.natural){natural=true;break;} await revealAll(game); await game.nextRound(); } assert.equal(natural,true); assert.equal(game.dealQueue.length,4); });
test("ROUND_END keeps cards until NEXT ROUND completes collection", async () => { const game=new app.BaccaratGameController(); game.placeSelectedBet("PLAYER"); await game.prepareDeal(async()=>{}); await revealAll(game); const before=[...game.dealtKeys]; assert.equal(game.state,app.GAME_STATES.ROUND_END); let release; const collecting=game.nextRound(()=>new Promise(resolve=>{release=resolve})); assert.equal(game.state,app.GAME_STATES.DISCARDING); assert.deepEqual([...game.dealtKeys],before); release(); await collecting; assert.equal(game.state,app.GAME_STATES.BETTING); assert.equal(game.dealtKeys.size,0); assert.equal(game.revealedKeys.size,0); });
test("discard sequence contains only dealt cards in Player then Banker order", () => { const plan=app.buildDealQueue({playerCards:[{}, {}, {}],bankerCards:[{}, {}, {}]}); const keys=new Set(["PLAYER-0","PLAYER-1","PLAYER-2","BANKER-0","BANKER-1","BANKER-2"]); assert.deepEqual(app.getDiscardSequence(plan,keys).map(item=>`${item.side}-${item.cardIndex}`),["PLAYER-0","PLAYER-1","PLAYER-2","BANKER-0","BANKER-1","BANKER-2"]); keys.delete("PLAYER-2"); assert.equal(app.getDiscardSequence(plan,keys).some(item=>item.side==="PLAYER"&&item.cardIndex===2),false); });
test("30 auto-deal/manual-reveal rounds remain stable", async () => { const game=new app.BaccaratGameController(); for(let i=1;i<=30;i++){ game.selectChip(10); assert.equal(game.placeSelectedBet(i%2?"PLAYER":"BANKER"),true); await game.prepareDeal(async()=>{}); await revealAll(game); assert.equal(game.state,app.GAME_STATES.ROUND_END); assert.ok(Number.isFinite(game.account.balance)); await game.nextRound(); } assert.equal(game.roundId,31); });
(async()=>{for(const {name,fn} of jobs){try{await fn();passed++;console.log(`PASS: ${name}`)}catch(error){failed++;console.error(`FAIL: ${name} — ${error.message}`)}}console.log(`\nTEST SUMMARY: Passed: ${passed}; Failed: ${failed}`);if(failed)process.exitCode=1})();
